project_id = "pjdyfuplrpwiksqxgept"

[functions.ai-chat]
verify_jwt = false

[functions.live-bank-rates]
verify_jwt = false

[functions.admin-stats]
verify_jwt = true

[functions.live-investment-rates]
verify_jwt = false

[functions.live-insurance-rates]
verify_jwt = false

[functions.live-loan-rates]
verify_jwt = false
